//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by YokiFrame TableKit.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Reflection;
using System.Collections.Generic;
using System.Threading;
using Luban;
using UnityEngine;
#if YOKIFRAME_UNITASK_SUPPORT
using Cysharp.Threading.Tasks;
#endif

/// <summary>
/// 配置表系统入口类
/// 由 TableKit 工具自动生成，路径配置已嵌入代码
/// </summary>
public static class TableKit
{
    private static cfg.Tables sTables;
    private static Func<string, byte[]> sBinaryLoader;
    private static Func<string, string> sJsonLoader;

    /// <summary>
    /// 是否已初始化
    /// </summary>
    public static bool Initialized { get; private set; }

    /// <summary>
    /// 运行时路径模式（生成时嵌入）
    /// </summary>
    public static string RuntimePathPattern { get; set; } = "Assets/AssetsPackage/Main/Configs/{0}";

    /// <summary>
    /// 获取配置表实例
    /// </summary>
    public static cfg.Tables Tables
    {
        get
        {
            if (sTables == null) Init();
            return sTables;
        }
    }

    /// <summary>
    /// 设置二进制数据加载器
    /// </summary>
    public static void SetBinaryLoader(Func<string, byte[]> loader)
    {
        sBinaryLoader = loader ?? throw new ArgumentNullException(nameof(loader));
    }

    /// <summary>
    /// 设置 JSON 数据加载器
    /// </summary>
    public static void SetJsonLoader(Func<string, string> loader)
    {
        sJsonLoader = loader ?? throw new ArgumentNullException(nameof(loader));
    }

    /// <summary>
    /// 初始化配置表
    /// </summary>
    public static void Init()
    {
        if (Initialized) return;

        if (sBinaryLoader == null) sBinaryLoader = DefaultBinaryLoader;
        if (sJsonLoader == null) sJsonLoader = DefaultJsonLoader;

        var tablesCtor = typeof(cfg.Tables).GetConstructors()[0];
        var loaderReturnType = tablesCtor.GetParameters()[0].ParameterType.GetGenericArguments()[1];

        object loader = loaderReturnType == typeof(ByteBuf)
            ? new Func<string, ByteBuf>(LoadBinary)
            : CreateJsonLoader(loaderReturnType);

        sTables = (cfg.Tables)tablesCtor.Invoke(new object[] { loader });
        Initialized = true;
    }

    private static MethodInfo sJsonParseMethod;

    private static object CreateJsonLoader(Type jsonNodeType)
    {
        var funcType = typeof(Func<,>).MakeGenericType(typeof(string), jsonNodeType);
        var loadJsonMethod = typeof(TableKit).GetMethod(nameof(LoadJsonDynamic),
            BindingFlags.NonPublic | BindingFlags.Static);
        return Delegate.CreateDelegate(funcType, loadJsonMethod);
    }

    private static object LoadJsonDynamic(string fileName)
    {
        var json = sJsonLoader(fileName);
        if (string.IsNullOrEmpty(json))
        {
            Debug.LogError($"[TableKit] 加载配置表失败: {fileName}");
            return null;
        }

        if (sJsonParseMethod == null)
        {
            var jsonType = AppDomain.CurrentDomain.GetAssemblies()
                .Where(a => !a.IsDynamic)
                .SelectMany(a => { try { return a.GetTypes(); } catch { return Type.EmptyTypes; } })
                .FirstOrDefault(t => t.FullName == "Luban.SimpleJson.JSON" || t.FullName == "SimpleJSON.JSON");

            if (jsonType == null)
                throw new InvalidOperationException("无法找到 JSON 类型");

            sJsonParseMethod = jsonType.GetMethod("Parse", BindingFlags.Public | BindingFlags.Static,
                null, new[] { typeof(string) }, null);
        }

        return sJsonParseMethod.Invoke(null, new object[] { json });
    }

    private static ByteBuf LoadBinary(string fileName)
    {
        var bytes = sBinaryLoader(fileName);
        if (bytes == null || bytes.Length == 0)
        {
            Debug.LogError($"[TableKit] 加载配置表失败: {fileName}");
            return null;
        }
        return new ByteBuf(bytes);
    }

    #region 默认加载器

    // 默认加载器：使用 Resources
    private static byte[] DefaultBinaryLoader(string fileName)
    {
        var path = string.Format(RuntimePathPattern, fileName);
        var asset = Resources.Load<TextAsset>(path);
        return asset != null ? asset.bytes : null;
    }

    private static string DefaultJsonLoader(string fileName)
    {
        var path = string.Format(RuntimePathPattern, fileName);
        var asset = Resources.Load<TextAsset>(path);
        return asset != null ? asset.text : null;
    }

    #endregion

#if YOKIFRAME_UNITASK_SUPPORT

    #region 异步加载

    /// <summary>
    /// 表文件名列表（生成时嵌入，用于异步预加载，可通过 SetTableFileNames 覆盖）
    /// </summary>
    private static string[] TABLE_FILE_NAMES = { "test_textitems" };
    private static string[] sCustomTableFileNames;

    private static Func<string, CancellationToken, UniTask<byte[]>> sAsyncBinaryLoader;
    private static Func<string, CancellationToken, UniTask<string>> sAsyncJsonLoader;

    /// <summary>
    /// 设置异步二进制数据加载器
    /// </summary>
    public static void SetAsyncBinaryLoader(Func<string, CancellationToken, UniTask<byte[]>> loader)
    {
        sAsyncBinaryLoader = loader ?? throw new ArgumentNullException(nameof(loader));
    }

    /// <summary>
    /// 设置异步 JSON 数据加载器
    /// </summary>
    public static void SetAsyncJsonLoader(Func<string, CancellationToken, UniTask<string>> loader)
    {
        sAsyncJsonLoader = loader ?? throw new ArgumentNullException(nameof(loader));
    }

    /// <summary>
    /// 设置表文件名列表（覆盖生成时嵌入的默认列表）
    /// </summary>
    public static void SetTableFileNames(string[] fileNames)
    {
        sCustomTableFileNames = fileNames ?? throw new ArgumentNullException(nameof(fileNames));
    }

    /// <summary>
    /// 异步初始化配置表（预缓存策略：先异步加载所有数据，再同步构造 Tables）
    /// </summary>
    public static async UniTask InitAsync(CancellationToken cancellationToken = default)
    {
        if (Initialized) return;

        if (sAsyncBinaryLoader == null) sAsyncBinaryLoader = DefaultAsyncBinaryLoader;
        if (sAsyncJsonLoader == null) sAsyncJsonLoader = DefaultAsyncJsonLoader;

        var tablesCtor = typeof(cfg.Tables).GetConstructors()[0];
        var loaderReturnType = tablesCtor.GetParameters()[0].ParameterType.GetGenericArguments()[1];
        var isBinary = loaderReturnType == typeof(ByteBuf);

        var fileNames = sCustomTableFileNames ?? TABLE_FILE_NAMES;

        // Phase 1: 并发异步加载所有表数据到缓存
        if (isBinary)
        {
            var cache = new Dictionary<string, byte[]>(fileNames.Length);
            var tasks = new UniTask[fileNames.Length];
            for (int i = 0; i < fileNames.Length; i++)
            {
                var fileName = fileNames[i];
                tasks[i] = LoadAndCacheBinaryAsync(fileName, cache, cancellationToken);
            }
            await UniTask.WhenAll(tasks);

            // Phase 2: 用缓存数据同步构造 Tables
            sTables = (cfg.Tables)tablesCtor.Invoke(new object[]
            {
                new Func<string, ByteBuf>(name =>
                {
                    if (!cache.TryGetValue(name, out var bytes) || bytes == null)
                    {
                        Debug.LogError($"[TableKit] 异步缓存未命中: {name}");
                        return null;
                    }
                    return new ByteBuf(bytes);
                })
            });
        }
        else
        {
            var cache = new Dictionary<string, string>(fileNames.Length);
            var tasks = new UniTask[fileNames.Length];
            for (int i = 0; i < fileNames.Length; i++)
            {
                var fileName = fileNames[i];
                tasks[i] = LoadAndCacheJsonAsync(fileName, cache, cancellationToken);
            }
            await UniTask.WhenAll(tasks);

            // 创建动态委托
            var funcType = typeof(Func<,>).MakeGenericType(typeof(string), loaderReturnType);
            var delegateMethod = new Func<string, object>(name =>
            {
                if (!cache.TryGetValue(name, out var json) || string.IsNullOrEmpty(json))
                {
                    Debug.LogError($"[TableKit] 异步缓存未命中: {name}");
                    return null;
                }

                if (sJsonParseMethod == null)
                {
                    var jsonType = AppDomain.CurrentDomain.GetAssemblies()
                        .Where(a => !a.IsDynamic)
                        .SelectMany(a => { try { return a.GetTypes(); } catch { return Type.EmptyTypes; } })
                        .FirstOrDefault(t => t.FullName == "Luban.SimpleJson.JSON" || t.FullName == "SimpleJSON.JSON");

                    if (jsonType == null)
                        throw new InvalidOperationException("无法找到 JSON 类型");

                    sJsonParseMethod = jsonType.GetMethod("Parse", BindingFlags.Public | BindingFlags.Static,
                        null, new[] { typeof(string) }, null);
                }

                return sJsonParseMethod.Invoke(null, new object[] { json });
            });

            var loaderDelegate = Delegate.CreateDelegate(funcType, delegateMethod.Target, delegateMethod.Method);
            sTables = (cfg.Tables)tablesCtor.Invoke(new object[] { loaderDelegate });
        }

        Initialized = true;
    }

    private static async UniTask LoadAndCacheBinaryAsync(
        string fileName, Dictionary<string, byte[]> cache, CancellationToken ct)
    {
        var bytes = await sAsyncBinaryLoader(fileName, ct);
        cache[fileName] = bytes;
    }

    private static async UniTask LoadAndCacheJsonAsync(
        string fileName, Dictionary<string, string> cache, CancellationToken ct)
    {
        var json = await sAsyncJsonLoader(fileName, ct);
        cache[fileName] = json;
    }

    // 默认异步加载器：使用 Resources.LoadAsync
    private static async UniTask<byte[]> DefaultAsyncBinaryLoader(string fileName, CancellationToken ct)
    {
        var path = string.Format(RuntimePathPattern, fileName);
        var request = Resources.LoadAsync<TextAsset>(path);
        await request.ToUniTask(cancellationToken: ct);
        var textAsset = request.asset as TextAsset;
        return textAsset != null ? textAsset.bytes : null;
    }

    private static async UniTask<string> DefaultAsyncJsonLoader(string fileName, CancellationToken ct)
    {
        var path = string.Format(RuntimePathPattern, fileName);
        var request = Resources.LoadAsync<TextAsset>(path);
        await request.ToUniTask(cancellationToken: ct);
        var textAsset = request.asset as TextAsset;
        return textAsset != null ? textAsset.text : null;
    }

    #endregion

#endif

    /// <summary>
    /// 重新加载配置表
    /// </summary>
    public static void Reload(Action onComplete = null)
    {
        try
        {
            sTables = null;
            Initialized = false;
            Init();
        }
        catch (Exception ex)
        {
            Debug.LogError($"[TableKit] Reload failed: {ex.Message}");
        }
        onComplete?.Invoke();
    }

#if YOKIFRAME_UNITASK_SUPPORT
    /// <summary>
    /// 异步重新加载配置表
    /// </summary>
    public static async UniTask ReloadAsync(CancellationToken cancellationToken = default)
    {
        sTables = null;
        Initialized = false;
        await InitAsync(cancellationToken);
    }
#endif

    /// <summary>
    /// 清理所有数据
    /// </summary>
    public static void Clear()
    {
        sTables = null;
        Initialized = false;
#if UNITY_EDITOR
        sTablesEditor = null;
#endif
    }

#if UNITY_EDITOR
    private static cfg.Tables sTablesEditor;

    /// <summary>
    /// 编辑器数据路径（生成时嵌入）
    /// </summary>
    public static string EditorDataPath { get; set; } = "Assets/AssetsPackage/Main/Configs/";

    /// <summary>
    /// 获取编辑器模式下的配置表实例
    /// </summary>
    public static cfg.Tables TablesEditor
    {
        get
        {
            if (sTablesEditor == null) InitEditor();
            return sTablesEditor;
        }
    }

    private static void InitEditor()
    {
        if (sTablesEditor != null) return;

        var tablesCtor = typeof(cfg.Tables).GetConstructors()[0];
        var loaderReturnType = tablesCtor.GetParameters()[0].ParameterType.GetGenericArguments()[1];

        object loader = loaderReturnType == typeof(ByteBuf)
            ? new Func<string, ByteBuf>(LoadBinaryEditor)
            : CreateJsonLoaderEditor(loaderReturnType);

        sTablesEditor = (cfg.Tables)tablesCtor.Invoke(new object[] { loader });
    }

    private static object CreateJsonLoaderEditor(Type jsonNodeType)
    {
        var funcType = typeof(Func<,>).MakeGenericType(typeof(string), jsonNodeType);
        var loadJsonMethod = typeof(TableKit).GetMethod(nameof(LoadJsonEditorDynamic),
            BindingFlags.NonPublic | BindingFlags.Static);
        return Delegate.CreateDelegate(funcType, loadJsonMethod);
    }

    private static object LoadJsonEditorDynamic(string fileName)
    {
        var path = $"{EditorDataPath}{fileName}.json";
        var asset = UnityEditor.AssetDatabase.LoadAssetAtPath<TextAsset>(path);
        if (asset == null)
        {
            Debug.LogError($"[TableKit] 编辑器加载配置表失败: {path}");
            return null;
        }

        if (sJsonParseMethod == null)
        {
            var jsonType = AppDomain.CurrentDomain.GetAssemblies()
                .Where(a => !a.IsDynamic)
                .SelectMany(a => { try { return a.GetTypes(); } catch { return Type.EmptyTypes; } })
                .FirstOrDefault(t => t.FullName == "Luban.SimpleJson.JSON" || t.FullName == "SimpleJSON.JSON");

            if (jsonType == null)
                throw new InvalidOperationException("无法找到 JSON 类型");

            sJsonParseMethod = jsonType.GetMethod("Parse", BindingFlags.Public | BindingFlags.Static,
                null, new[] { typeof(string) }, null);
        }

        return sJsonParseMethod.Invoke(null, new object[] { asset.text });
    }

    private static ByteBuf LoadBinaryEditor(string fileName)
    {
        var path = $"{EditorDataPath}{fileName}.bytes";
        var asset = UnityEditor.AssetDatabase.LoadAssetAtPath<TextAsset>(path);
        if (asset == null)
        {
            Debug.LogError($"[TableKit] 编辑器加载配置表失败: {path}");
            return null;
        }
        return new ByteBuf(asset.bytes);
    }

    /// <summary>
    /// 刷新编辑器缓存
    /// </summary>
    public static void RefreshEditor() => sTablesEditor = null;
#endif
}
