// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: item.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CommonPB {

  /// <summary>Holder for reflection information generated from item.proto</summary>
  public static partial class ItemReflection {

    #region Descriptor
    /// <summary>File descriptor for item.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ItemReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgppdGVtLnByb3RvEghjb21tb25QQiJBCgRJdGVtEgoKAmlkGAEgASgDEgsK",
            "A2NpZBgCIAEoAxINCgV2YWx1ZRgDIAEoAxIRCglleHBpcmVfYXQYBCABKAMi",
            "JwoJU21hbGxJdGVtEgsKA2NpZBgBIAEoAxINCgV2YWx1ZRgCIAEoAyJACgpJ",
            "dGVtQ2hhbmdlEhwKBGl0ZW0YASABKAsyDi5jb21tb25QQi5JdGVtEhQKDGNo",
            "YW5nZV92YWx1ZRgCIAEoAyKHAQoLSXRlbUNoYW5nZXMSIwoFaXRlbXMYASAD",
            "KAsyFC5jb21tb25QQi5JdGVtQ2hhbmdlEioKBnNvdXJjZRgCIAEoDjIaLmNv",
            "bW1vblBCLkl0ZW1DaGFuZ2VTb3VyY2USJwoKaG9va19pdGVtcxgDIAMoCzIT",
            "LmNvbW1vblBCLlNtYWxsSXRlbSrMCgoQSXRlbUNoYW5nZVNvdXJjZRIRCg1T",
            "b3VyY2VVbmtub3duEAASEgoOU291cmNlUmVnaXN0ZXIQARIWChJTb3VyY2VS",
            "ZWNlaXZlRW1haWwQAhIWChJTb3VyY2VCYWNrcGFja1NlbGwQAxIVChFTb3Vy",
            "Y2VCYWNrcGFja1VzZRAEEg8KC1NvdXJjZUNoZWF0EAUSGQoVU291cmNlTWFp",
            "blN0YWdlUmV3YXJkEAYSGAoUU291cmNlTWFpblN0YWdlU3RhcnQQBxIWChJT",
            "b3VyY2VNYWluU3RhZ2VFbmQQCBIZChVTb3VyY2VTdGFnZVN0YXJSZXdhcmQQ",
            "CRIbChdTb3VyY2VTZXZlblNpZ25JblJld2FyZBAKEg8KC1NvdXJjZUNES2V5",
            "EAsSGAoUU291cmNlQ2hvb3NlVHJlYXN1cmUQDBIVChFTb3VyY2VJbWFnZVVu",
            "bG9jaxAPEhoKFlNvdXJjZUltYWdlU3VpdFVwZ3JhZGUQEBISCg5Tb3VyY2VJ",
            "bml0SGVhZBAREhcKE1NvdXJjZVJlbGljTHZDaGFuZ2UQZRIaChZTb3VyY2VS",
            "ZWxpY1RyYW5zQ2hhbmdlEGYSGgoWU291cmNlUmVsaWNBd2FrZUNoYW5nZRBn",
            "EhgKE1NvdXJjZU1vdW50THZDaGFuZ2UQyQESGwoWU291cmNlTW91bnRUcmFu",
            "c0NoYW5nZRDKARIbChZTb3VyY2VNb3VudEF3YWtlQ2hhbmdlEMsBEhYKEVNv",
            "dXJjZU1vdW50VW5sb2NrEMwBEhUKEFNvdXJjZVJhbmRvbVBldHMQrAISIAob",
            "U291cmNlU3dhbGxvd1BldFJldHVybkl0ZW1zEK0CEhgKE1NvdXJjZURlY29t",
            "cG9zZVBldHMQrgISGAoTU291cmNlUmVzZXRQZXRMZXZlbBCvAhIWChFTb3Vy",
            "Y2VVcGdyYWRlZFBldBCwAhIZChRTb3VyY2VFcXVpcEx2VXBncmFkZRD1AxIb",
            "ChZTb3VyY2VFcXVpcFRpZXJVcGdyYWRlEPYDEhsKFlNvdXJjZUVxdWlwUmFy",
            "ZVVwZ3JhZGUQ9wMSFwoSU291cmNlRXF1aXBMdlJlc2V0EPgDEhkKFFNvdXJj",
            "ZUVxdWlwRGVjb21wb3NlEPkDEhUKEVNvdXJjZVJlbGljVW5sb2NrEGgSGAoT",
            "U291cmNlVGFsZW50VXBncmFkZRDZBBIaChVTb3VyY2VTaG9wQWN0aXZpdHlC",
            "b3gQvQUSGAoTU291cmNlU2hvcENvbW1vbkJveBC+BRIaChVTb3VyY2VTaG9w",
            "QWR2YW5jZWRCb3gQvwUSGgoVU291cmNlU2hvcENoYXB0ZXJHaWZ0EMAFEhwK",
            "F1NvdXJjZVNob3BDaG9vc2VVcEVxdWlwEMEFEhcKElNvdXJjZVRyYXZlbEZp",
            "bmlzaBChBhIVChBTb3VyY2VUcmF2ZWxDb3N0EKIGEh8KGlNvdXJjZURyYXdE",
            "YWlseVRhc2tSZXdhcmRzEIcHEiUKIFNvdXJjZURyYXdEYWlseVRhc2tBY3Rp",
            "dmVSZXdhcmRzEIgHEiAKG1NvdXJjZURyYXdXZWVrbHlUYXNrUmV3YXJkcxCJ",
            "BxImCiFTb3VyY2VEcmF3V2Vla2x5VGFza0FjdGl2ZVJld2FyZHMQigcSIQoc",
            "U291cmNlRHJhd0FjaGlldmVtZW50UmV3YXJkcxCLBxIiCh1Tb3VyY2VTZWxl",
            "Y3RUcmF2ZWxBY2hpZXZlbWVudBCMBxIYChNTb3VyY2VPcGVuT2JqZWN0Qm94",
            "EM0IEhcKElNvdXJjZU9wZW5Qb2ludEJveBDOCEIZWhdwM3NlcnZlci9wcm90",
            "by9jb21tb25QQmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::CommonPB.ItemChangeSource), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CommonPB.Item), global::CommonPB.Item.Parser, new[]{ "Id", "Cid", "Value", "ExpireAt" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CommonPB.SmallItem), global::CommonPB.SmallItem.Parser, new[]{ "Cid", "Value" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CommonPB.ItemChange), global::CommonPB.ItemChange.Parser, new[]{ "Item", "ChangeValue" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CommonPB.ItemChanges), global::CommonPB.ItemChanges.Parser, new[]{ "Items", "Source", "HookItems" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ItemChangeSource {
    /// <summary>
    /// 其他类型
    /// </summary>
    [pbr::OriginalName("SourceUnknown")] SourceUnknown = 0,
    /// <summary>
    /// 玩家注册
    /// </summary>
    [pbr::OriginalName("SourceRegister")] SourceRegister = 1,
    /// <summary>
    /// 领取邮件奖励
    /// </summary>
    [pbr::OriginalName("SourceReceiveEmail")] SourceReceiveEmail = 2,
    /// <summary>
    /// 背包售卖
    /// </summary>
    [pbr::OriginalName("SourceBackpackSell")] SourceBackpackSell = 3,
    /// <summary>
    /// 背包使用
    /// </summary>
    [pbr::OriginalName("SourceBackpackUse")] SourceBackpackUse = 4,
    /// <summary>
    /// 使用作弊器操作
    /// </summary>
    [pbr::OriginalName("SourceCheat")] SourceCheat = 5,
    /// <summary>
    /// 主章节阶段奖励
    /// </summary>
    [pbr::OriginalName("SourceMainStageReward")] SourceMainStageReward = 6,
    /// <summary>
    /// 章节开始
    /// </summary>
    [pbr::OriginalName("SourceMainStageStart")] SourceMainStageStart = 7,
    /// <summary>
    /// 章节结束
    /// </summary>
    [pbr::OriginalName("SourceMainStageEnd")] SourceMainStageEnd = 8,
    /// <summary>
    /// 星星奖励
    /// </summary>
    [pbr::OriginalName("SourceStageStarReward")] SourceStageStarReward = 9,
    /// <summary>
    /// 七日签到奖励
    /// </summary>
    [pbr::OriginalName("SourceSevenSignInReward")] SourceSevenSignInReward = 10,
    /// <summary>
    /// 兑换码奖励
    /// </summary>
    [pbr::OriginalName("SourceCDKey")] SourceCdkey = 11,
    /// <summary>
    /// 选择型宝箱
    /// </summary>
    [pbr::OriginalName("SourceChooseTreasure")] SourceChooseTreasure = 12,
    /// <summary>
    /// 个人装饰解锁
    /// </summary>
    [pbr::OriginalName("SourceImageUnlock")] SourceImageUnlock = 15,
    /// <summary>
    /// 套装升级
    /// </summary>
    [pbr::OriginalName("SourceImageSuitUpgrade")] SourceImageSuitUpgrade = 16,
    /// <summary>
    /// 初始化头像
    /// </summary>
    [pbr::OriginalName("SourceInitHead")] SourceInitHead = 17,
    /// <summary>
    /// 神器升级消耗
    /// </summary>
    [pbr::OriginalName("SourceRelicLvChange")] SourceRelicLvChange = 101,
    /// <summary>
    /// 神器幻化消耗
    /// </summary>
    [pbr::OriginalName("SourceRelicTransChange")] SourceRelicTransChange = 102,
    /// <summary>
    /// 神器觉醒消耗
    /// </summary>
    [pbr::OriginalName("SourceRelicAwakeChange")] SourceRelicAwakeChange = 103,
    /// <summary>
    /// 坐骑升级消耗
    /// </summary>
    [pbr::OriginalName("SourceMountLvChange")] SourceMountLvChange = 201,
    /// <summary>
    /// 坐骑幻化消耗
    /// </summary>
    [pbr::OriginalName("SourceMountTransChange")] SourceMountTransChange = 202,
    /// <summary>
    /// 坐骑觉醒消耗
    /// </summary>
    [pbr::OriginalName("SourceMountAwakeChange")] SourceMountAwakeChange = 203,
    /// <summary>
    /// 坐骑解锁消耗
    /// </summary>
    [pbr::OriginalName("SourceMountUnlock")] SourceMountUnlock = 204,
    /// <summary>
    /// 抽宠物消耗道具
    /// </summary>
    [pbr::OriginalName("SourceRandomPets")] SourceRandomPets = 300,
    /// <summary>
    /// 吞噬退回升级道具
    /// </summary>
    [pbr::OriginalName("SourceSwallowPetReturnItems")] SourceSwallowPetReturnItems = 301,
    /// <summary>
    /// 分解宠物
    /// </summary>
    [pbr::OriginalName("SourceDecomposePets")] SourceDecomposePets = 302,
    /// <summary>
    /// 重置宠物等级
    /// </summary>
    [pbr::OriginalName("SourceResetPetLevel")] SourceResetPetLevel = 303,
    /// <summary>
    /// 宠物升级消耗
    /// </summary>
    [pbr::OriginalName("SourceUpgradedPet")] SourceUpgradedPet = 304,
    /// <summary>
    /// 装备升级
    /// </summary>
    [pbr::OriginalName("SourceEquipLvUpgrade")] SourceEquipLvUpgrade = 501,
    /// <summary>
    /// 装备升阶
    /// </summary>
    [pbr::OriginalName("SourceEquipTierUpgrade")] SourceEquipTierUpgrade = 502,
    /// <summary>
    /// 装备升品
    /// </summary>
    [pbr::OriginalName("SourceEquipRareUpgrade")] SourceEquipRareUpgrade = 503,
    /// <summary>
    /// 装备重置等级
    /// </summary>
    [pbr::OriginalName("SourceEquipLvReset")] SourceEquipLvReset = 504,
    /// <summary>
    /// 装备分解
    /// </summary>
    [pbr::OriginalName("SourceEquipDecompose")] SourceEquipDecompose = 505,
    /// <summary>
    /// 神器解锁消耗
    /// </summary>
    [pbr::OriginalName("SourceRelicUnlock")] SourceRelicUnlock = 104,
    /// <summary>
    /// 天赋升级
    /// </summary>
    [pbr::OriginalName("SourceTalentUpgrade")] SourceTalentUpgrade = 601,
    [pbr::OriginalName("SourceShopActivityBox")] SourceShopActivityBox = 701,
    [pbr::OriginalName("SourceShopCommonBox")] SourceShopCommonBox = 702,
    [pbr::OriginalName("SourceShopAdvancedBox")] SourceShopAdvancedBox = 703,
    [pbr::OriginalName("SourceShopChapterGift")] SourceShopChapterGift = 704,
    [pbr::OriginalName("SourceShopChooseUpEquip")] SourceShopChooseUpEquip = 705,
    /// <summary>
    /// 游历
    /// </summary>
    [pbr::OriginalName("SourceTravelFinish")] SourceTravelFinish = 801,
    [pbr::OriginalName("SourceTravelCost")] SourceTravelCost = 802,
    /// <summary>
    /// 领取日常任务奖励
    /// </summary>
    [pbr::OriginalName("SourceDrawDailyTaskRewards")] SourceDrawDailyTaskRewards = 903,
    /// <summary>
    /// 领取日常任务活跃度奖励
    /// </summary>
    [pbr::OriginalName("SourceDrawDailyTaskActiveRewards")] SourceDrawDailyTaskActiveRewards = 904,
    /// <summary>
    /// 领取周常任务奖励
    /// </summary>
    [pbr::OriginalName("SourceDrawWeeklyTaskRewards")] SourceDrawWeeklyTaskRewards = 905,
    /// <summary>
    /// 领取周常任务活跃度奖励
    /// </summary>
    [pbr::OriginalName("SourceDrawWeeklyTaskActiveRewards")] SourceDrawWeeklyTaskActiveRewards = 906,
    /// <summary>
    /// 领取成就奖励
    /// </summary>
    [pbr::OriginalName("SourceDrawAchievementRewards")] SourceDrawAchievementRewards = 907,
    /// <summary>
    /// 选择随机旅行事件成就
    /// </summary>
    [pbr::OriginalName("SourceSelectTravelAchievement")] SourceSelectTravelAchievement = 908,
    /// <summary>
    /// 藏品宝箱
    /// </summary>
    [pbr::OriginalName("SourceOpenObjectBox")] SourceOpenObjectBox = 1101,
    /// <summary>
    /// 藏品宝箱
    /// </summary>
    [pbr::OriginalName("SourceOpenPointBox")] SourceOpenPointBox = 1102,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Item : pb::IMessage<Item>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Item> _parser = new pb::MessageParser<Item>(() => new Item());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Item> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CommonPB.ItemReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Item() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Item(Item other) : this() {
      id_ = other.id_;
      cid_ = other.cid_;
      value_ = other.value_;
      expireAt_ = other.expireAt_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Item Clone() {
      return new Item(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "cid" field.</summary>
    public const int CidFieldNumber = 2;
    private long cid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Cid {
      get { return cid_; }
      set {
        cid_ = value;
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 3;
    private long value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    /// <summary>Field number for the "expire_at" field.</summary>
    public const int ExpireAtFieldNumber = 4;
    private long expireAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ExpireAt {
      get { return expireAt_; }
      set {
        expireAt_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Item);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Item other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Cid != other.Cid) return false;
      if (Value != other.Value) return false;
      if (ExpireAt != other.ExpireAt) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (Cid != 0L) hash ^= Cid.GetHashCode();
      if (Value != 0L) hash ^= Value.GetHashCode();
      if (ExpireAt != 0L) hash ^= ExpireAt.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Cid != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Cid);
      }
      if (Value != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Value);
      }
      if (ExpireAt != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(ExpireAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Cid != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Cid);
      }
      if (Value != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Value);
      }
      if (ExpireAt != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(ExpireAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (Cid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Cid);
      }
      if (Value != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Value);
      }
      if (ExpireAt != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ExpireAt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Item other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.Cid != 0L) {
        Cid = other.Cid;
      }
      if (other.Value != 0L) {
        Value = other.Value;
      }
      if (other.ExpireAt != 0L) {
        ExpireAt = other.ExpireAt;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            Cid = input.ReadInt64();
            break;
          }
          case 24: {
            Value = input.ReadInt64();
            break;
          }
          case 32: {
            ExpireAt = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            Cid = input.ReadInt64();
            break;
          }
          case 24: {
            Value = input.ReadInt64();
            break;
          }
          case 32: {
            ExpireAt = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SmallItem : pb::IMessage<SmallItem>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SmallItem> _parser = new pb::MessageParser<SmallItem>(() => new SmallItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SmallItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CommonPB.ItemReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SmallItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SmallItem(SmallItem other) : this() {
      cid_ = other.cid_;
      value_ = other.value_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SmallItem Clone() {
      return new SmallItem(this);
    }

    /// <summary>Field number for the "cid" field.</summary>
    public const int CidFieldNumber = 1;
    private long cid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Cid {
      get { return cid_; }
      set {
        cid_ = value;
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 2;
    private long value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SmallItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SmallItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Cid != other.Cid) return false;
      if (Value != other.Value) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Cid != 0L) hash ^= Cid.GetHashCode();
      if (Value != 0L) hash ^= Value.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Cid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Cid);
      }
      if (Value != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Cid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Cid);
      }
      if (Value != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Cid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Cid);
      }
      if (Value != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Value);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SmallItem other) {
      if (other == null) {
        return;
      }
      if (other.Cid != 0L) {
        Cid = other.Cid;
      }
      if (other.Value != 0L) {
        Value = other.Value;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Cid = input.ReadInt64();
            break;
          }
          case 16: {
            Value = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Cid = input.ReadInt64();
            break;
          }
          case 16: {
            Value = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ItemChange : pb::IMessage<ItemChange>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ItemChange> _parser = new pb::MessageParser<ItemChange>(() => new ItemChange());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ItemChange> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CommonPB.ItemReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemChange() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemChange(ItemChange other) : this() {
      item_ = other.item_ != null ? other.item_.Clone() : null;
      changeValue_ = other.changeValue_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemChange Clone() {
      return new ItemChange(this);
    }

    /// <summary>Field number for the "item" field.</summary>
    public const int ItemFieldNumber = 1;
    private global::CommonPB.Item item_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CommonPB.Item Item {
      get { return item_; }
      set {
        item_ = value;
      }
    }

    /// <summary>Field number for the "change_value" field.</summary>
    public const int ChangeValueFieldNumber = 2;
    private long changeValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ChangeValue {
      get { return changeValue_; }
      set {
        changeValue_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ItemChange);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ItemChange other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Item, other.Item)) return false;
      if (ChangeValue != other.ChangeValue) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (item_ != null) hash ^= Item.GetHashCode();
      if (ChangeValue != 0L) hash ^= ChangeValue.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (item_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Item);
      }
      if (ChangeValue != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ChangeValue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (item_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Item);
      }
      if (ChangeValue != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ChangeValue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (item_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Item);
      }
      if (ChangeValue != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ChangeValue);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ItemChange other) {
      if (other == null) {
        return;
      }
      if (other.item_ != null) {
        if (item_ == null) {
          Item = new global::CommonPB.Item();
        }
        Item.MergeFrom(other.Item);
      }
      if (other.ChangeValue != 0L) {
        ChangeValue = other.ChangeValue;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (item_ == null) {
              Item = new global::CommonPB.Item();
            }
            input.ReadMessage(Item);
            break;
          }
          case 16: {
            ChangeValue = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (item_ == null) {
              Item = new global::CommonPB.Item();
            }
            input.ReadMessage(Item);
            break;
          }
          case 16: {
            ChangeValue = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ItemChanges : pb::IMessage<ItemChanges>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ItemChanges> _parser = new pb::MessageParser<ItemChanges>(() => new ItemChanges());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ItemChanges> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CommonPB.ItemReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemChanges() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemChanges(ItemChanges other) : this() {
      items_ = other.items_.Clone();
      source_ = other.source_;
      hookItems_ = other.hookItems_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemChanges Clone() {
      return new ItemChanges(this);
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::CommonPB.ItemChange> _repeated_items_codec
        = pb::FieldCodec.ForMessage(10, global::CommonPB.ItemChange.Parser);
    private readonly pbc::RepeatedField<global::CommonPB.ItemChange> items_ = new pbc::RepeatedField<global::CommonPB.ItemChange>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CommonPB.ItemChange> Items {
      get { return items_; }
    }

    /// <summary>Field number for the "source" field.</summary>
    public const int SourceFieldNumber = 2;
    private global::CommonPB.ItemChangeSource source_ = global::CommonPB.ItemChangeSource.SourceUnknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CommonPB.ItemChangeSource Source {
      get { return source_; }
      set {
        source_ = value;
      }
    }

    /// <summary>Field number for the "hook_items" field.</summary>
    public const int HookItemsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::CommonPB.SmallItem> _repeated_hookItems_codec
        = pb::FieldCodec.ForMessage(26, global::CommonPB.SmallItem.Parser);
    private readonly pbc::RepeatedField<global::CommonPB.SmallItem> hookItems_ = new pbc::RepeatedField<global::CommonPB.SmallItem>();
    /// <summary>
    /// 增加道具时，只有被hook之后才会出现在这里，减少的都不会出现在这里, 目前只是给前端做表现用
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CommonPB.SmallItem> HookItems {
      get { return hookItems_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ItemChanges);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ItemChanges other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!items_.Equals(other.items_)) return false;
      if (Source != other.Source) return false;
      if(!hookItems_.Equals(other.hookItems_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= items_.GetHashCode();
      if (Source != global::CommonPB.ItemChangeSource.SourceUnknown) hash ^= Source.GetHashCode();
      hash ^= hookItems_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      items_.WriteTo(output, _repeated_items_codec);
      if (Source != global::CommonPB.ItemChangeSource.SourceUnknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Source);
      }
      hookItems_.WriteTo(output, _repeated_hookItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      items_.WriteTo(ref output, _repeated_items_codec);
      if (Source != global::CommonPB.ItemChangeSource.SourceUnknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Source);
      }
      hookItems_.WriteTo(ref output, _repeated_hookItems_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_repeated_items_codec);
      if (Source != global::CommonPB.ItemChangeSource.SourceUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Source);
      }
      size += hookItems_.CalculateSize(_repeated_hookItems_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ItemChanges other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      if (other.Source != global::CommonPB.ItemChangeSource.SourceUnknown) {
        Source = other.Source;
      }
      hookItems_.Add(other.hookItems_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
          case 16: {
            Source = (global::CommonPB.ItemChangeSource) input.ReadEnum();
            break;
          }
          case 26: {
            hookItems_.AddEntriesFrom(input, _repeated_hookItems_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            items_.AddEntriesFrom(ref input, _repeated_items_codec);
            break;
          }
          case 16: {
            Source = (global::CommonPB.ItemChangeSource) input.ReadEnum();
            break;
          }
          case 26: {
            hookItems_.AddEntriesFrom(ref input, _repeated_hookItems_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
