// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: task.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CommonPB {

  /// <summary>Holder for reflection information generated from task.proto</summary>
  public static partial class TaskReflection {

    #region Descriptor
    /// <summary>File descriptor for task.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TaskReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgp0YXNrLnByb3RvEghjb21tb25QQiJJCghUYXNrQ29uZBIMCgRjb25kGAEg",
            "ASgFEg4KBnRhcmdldBgCIAEoAxILCgNudW0YAyABKAMSEgoKaXNfcmVwbGFj",
            "ZRgEIAEoCCJPCgRUYXNrEg8KB3Rhc2tfaWQYASABKAMSEAoIcHJvZ3Jlc3MY",
            "AiABKAMSJAoGc3RhdHVzGAMgASgOMhQuY29tbW9uUEIuVGFza1N0YXR1cyJr",
            "Cg1BY3RpdmVSZXdhcmRzEhQKDGFjdGl2ZV9wb2ludBgBIAEoAxIuCg5hY3Rp",
            "dmVfcmV3YXJkcxgCIAMoDjIWLmNvbW1vblBCLlJld2FyZFN0YXR1cxIUCgxu",
            "ZXh0X3JlZnJlc2gYAyABKAMqSQoKVGFza1N0YXR1cxIOCgpOb3RTdGFydGVk",
            "EAASDQoJQ29tcGxldGVkEAESDgoKUHJvY2Vzc2luZxACEgwKCEZpbmlzaGVk",
            "EAMqSAoMUmV3YXJkU3RhdHVzEhAKDFJld2FyZExvY2tlZBAAEhIKDlJld2Fy",
            "ZFVubG9ja2VkEAESEgoOUmV3YXJkUmVjZWl2ZWQQAkIZWhdwM3NlcnZlci9w",
            "cm90by9jb21tb25QQmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::CommonPB.TaskStatus), typeof(global::CommonPB.RewardStatus), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CommonPB.TaskCond), global::CommonPB.TaskCond.Parser, new[]{ "Cond", "Target", "Num", "IsReplace" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CommonPB.Task), global::CommonPB.Task.Parser, new[]{ "TaskId", "Progress", "Status" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CommonPB.ActiveRewards), global::CommonPB.ActiveRewards.Parser, new[]{ "ActivePoint", "ActiveRewards_", "NextRefresh" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 任务状态
  /// </summary>
  public enum TaskStatus {
    /// <summary>
    /// 未开启
    /// </summary>
    [pbr::OriginalName("NotStarted")] NotStarted = 0,
    /// <summary>
    /// 已完成 未领取奖励
    /// </summary>
    [pbr::OriginalName("Completed")] Completed = 1,
    /// <summary>
    /// 正在进行
    /// </summary>
    [pbr::OriginalName("Processing")] Processing = 2,
    /// <summary>
    /// 已结束
    /// </summary>
    [pbr::OriginalName("Finished")] Finished = 3,
  }

  /// <summary>
  /// 奖励状态
  /// </summary>
  public enum RewardStatus {
    /// <summary>
    /// 锁定
    /// </summary>
    [pbr::OriginalName("RewardLocked")] RewardLocked = 0,
    /// <summary>
    /// 可领取
    /// </summary>
    [pbr::OriginalName("RewardUnlocked")] RewardUnlocked = 1,
    /// <summary>
    /// 已领取
    /// </summary>
    [pbr::OriginalName("RewardReceived")] RewardReceived = 2,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TaskCond : pb::IMessage<TaskCond>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TaskCond> _parser = new pb::MessageParser<TaskCond>(() => new TaskCond());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TaskCond> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CommonPB.TaskReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskCond() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskCond(TaskCond other) : this() {
      cond_ = other.cond_;
      target_ = other.target_;
      num_ = other.num_;
      isReplace_ = other.isReplace_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskCond Clone() {
      return new TaskCond(this);
    }

    /// <summary>Field number for the "cond" field.</summary>
    public const int CondFieldNumber = 1;
    private int cond_;
    /// <summary>
    /// 任务条件 见表 __enums__.xlsx task_cond
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Cond {
      get { return cond_; }
      set {
        cond_ = value;
      }
    }

    /// <summary>Field number for the "target" field.</summary>
    public const int TargetFieldNumber = 2;
    private long target_;
    /// <summary>
    /// 目标id 0为无目标
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Target {
      get { return target_; }
      set {
        target_ = value;
      }
    }

    /// <summary>Field number for the "num" field.</summary>
    public const int NumFieldNumber = 3;
    private long num_;
    /// <summary>
    /// 完成次数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Num {
      get { return num_; }
      set {
        num_ = value;
      }
    }

    /// <summary>Field number for the "is_replace" field.</summary>
    public const int IsReplaceFieldNumber = 4;
    private bool isReplace_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsReplace {
      get { return isReplace_; }
      set {
        isReplace_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TaskCond);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TaskCond other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Cond != other.Cond) return false;
      if (Target != other.Target) return false;
      if (Num != other.Num) return false;
      if (IsReplace != other.IsReplace) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Cond != 0) hash ^= Cond.GetHashCode();
      if (Target != 0L) hash ^= Target.GetHashCode();
      if (Num != 0L) hash ^= Num.GetHashCode();
      if (IsReplace != false) hash ^= IsReplace.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Cond != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Cond);
      }
      if (Target != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Target);
      }
      if (Num != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Num);
      }
      if (IsReplace != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsReplace);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Cond != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Cond);
      }
      if (Target != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Target);
      }
      if (Num != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Num);
      }
      if (IsReplace != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsReplace);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Cond != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Cond);
      }
      if (Target != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Target);
      }
      if (Num != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Num);
      }
      if (IsReplace != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TaskCond other) {
      if (other == null) {
        return;
      }
      if (other.Cond != 0) {
        Cond = other.Cond;
      }
      if (other.Target != 0L) {
        Target = other.Target;
      }
      if (other.Num != 0L) {
        Num = other.Num;
      }
      if (other.IsReplace != false) {
        IsReplace = other.IsReplace;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Cond = input.ReadInt32();
            break;
          }
          case 16: {
            Target = input.ReadInt64();
            break;
          }
          case 24: {
            Num = input.ReadInt64();
            break;
          }
          case 32: {
            IsReplace = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Cond = input.ReadInt32();
            break;
          }
          case 16: {
            Target = input.ReadInt64();
            break;
          }
          case 24: {
            Num = input.ReadInt64();
            break;
          }
          case 32: {
            IsReplace = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Task : pb::IMessage<Task>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Task> _parser = new pb::MessageParser<Task>(() => new Task());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Task> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CommonPB.TaskReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Task() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Task(Task other) : this() {
      taskId_ = other.taskId_;
      progress_ = other.progress_;
      status_ = other.status_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Task Clone() {
      return new Task(this);
    }

    /// <summary>Field number for the "task_id" field.</summary>
    public const int TaskIdFieldNumber = 1;
    private long taskId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TaskId {
      get { return taskId_; }
      set {
        taskId_ = value;
      }
    }

    /// <summary>Field number for the "progress" field.</summary>
    public const int ProgressFieldNumber = 2;
    private long progress_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Progress {
      get { return progress_; }
      set {
        progress_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 3;
    private global::CommonPB.TaskStatus status_ = global::CommonPB.TaskStatus.NotStarted;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CommonPB.TaskStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Task);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Task other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TaskId != other.TaskId) return false;
      if (Progress != other.Progress) return false;
      if (Status != other.Status) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TaskId != 0L) hash ^= TaskId.GetHashCode();
      if (Progress != 0L) hash ^= Progress.GetHashCode();
      if (Status != global::CommonPB.TaskStatus.NotStarted) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TaskId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(TaskId);
      }
      if (Progress != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Progress);
      }
      if (Status != global::CommonPB.TaskStatus.NotStarted) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TaskId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(TaskId);
      }
      if (Progress != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Progress);
      }
      if (Status != global::CommonPB.TaskStatus.NotStarted) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TaskId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TaskId);
      }
      if (Progress != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Progress);
      }
      if (Status != global::CommonPB.TaskStatus.NotStarted) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Task other) {
      if (other == null) {
        return;
      }
      if (other.TaskId != 0L) {
        TaskId = other.TaskId;
      }
      if (other.Progress != 0L) {
        Progress = other.Progress;
      }
      if (other.Status != global::CommonPB.TaskStatus.NotStarted) {
        Status = other.Status;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TaskId = input.ReadInt64();
            break;
          }
          case 16: {
            Progress = input.ReadInt64();
            break;
          }
          case 24: {
            Status = (global::CommonPB.TaskStatus) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TaskId = input.ReadInt64();
            break;
          }
          case 16: {
            Progress = input.ReadInt64();
            break;
          }
          case 24: {
            Status = (global::CommonPB.TaskStatus) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 活跃度奖励
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ActiveRewards : pb::IMessage<ActiveRewards>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActiveRewards> _parser = new pb::MessageParser<ActiveRewards>(() => new ActiveRewards());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ActiveRewards> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CommonPB.TaskReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActiveRewards() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActiveRewards(ActiveRewards other) : this() {
      activePoint_ = other.activePoint_;
      activeRewards_ = other.activeRewards_.Clone();
      nextRefresh_ = other.nextRefresh_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActiveRewards Clone() {
      return new ActiveRewards(this);
    }

    /// <summary>Field number for the "active_point" field.</summary>
    public const int ActivePointFieldNumber = 1;
    private long activePoint_;
    /// <summary>
    /// 活跃度
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ActivePoint {
      get { return activePoint_; }
      set {
        activePoint_ = value;
      }
    }

    /// <summary>Field number for the "active_rewards" field.</summary>
    public const int ActiveRewards_FieldNumber = 2;
    private static readonly pb::FieldCodec<global::CommonPB.RewardStatus> _repeated_activeRewards_codec
        = pb::FieldCodec.ForEnum(18, x => (int) x, x => (global::CommonPB.RewardStatus) x);
    private readonly pbc::RepeatedField<global::CommonPB.RewardStatus> activeRewards_ = new pbc::RepeatedField<global::CommonPB.RewardStatus>();
    /// <summary>
    /// 活跃度奖励
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CommonPB.RewardStatus> ActiveRewards_ {
      get { return activeRewards_; }
    }

    /// <summary>Field number for the "next_refresh" field.</summary>
    public const int NextRefreshFieldNumber = 3;
    private long nextRefresh_;
    /// <summary>
    /// 下次刷新时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long NextRefresh {
      get { return nextRefresh_; }
      set {
        nextRefresh_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ActiveRewards);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ActiveRewards other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ActivePoint != other.ActivePoint) return false;
      if(!activeRewards_.Equals(other.activeRewards_)) return false;
      if (NextRefresh != other.NextRefresh) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ActivePoint != 0L) hash ^= ActivePoint.GetHashCode();
      hash ^= activeRewards_.GetHashCode();
      if (NextRefresh != 0L) hash ^= NextRefresh.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ActivePoint != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ActivePoint);
      }
      activeRewards_.WriteTo(output, _repeated_activeRewards_codec);
      if (NextRefresh != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(NextRefresh);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ActivePoint != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ActivePoint);
      }
      activeRewards_.WriteTo(ref output, _repeated_activeRewards_codec);
      if (NextRefresh != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(NextRefresh);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ActivePoint != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ActivePoint);
      }
      size += activeRewards_.CalculateSize(_repeated_activeRewards_codec);
      if (NextRefresh != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(NextRefresh);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ActiveRewards other) {
      if (other == null) {
        return;
      }
      if (other.ActivePoint != 0L) {
        ActivePoint = other.ActivePoint;
      }
      activeRewards_.Add(other.activeRewards_);
      if (other.NextRefresh != 0L) {
        NextRefresh = other.NextRefresh;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ActivePoint = input.ReadInt64();
            break;
          }
          case 18:
          case 16: {
            activeRewards_.AddEntriesFrom(input, _repeated_activeRewards_codec);
            break;
          }
          case 24: {
            NextRefresh = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ActivePoint = input.ReadInt64();
            break;
          }
          case 18:
          case 16: {
            activeRewards_.AddEntriesFrom(ref input, _repeated_activeRewards_codec);
            break;
          }
          case 24: {
            NextRefresh = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
