
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public Test.TextItems TextItems {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TextItems = new Test.TextItems(loader("test_textitems"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TextItems.ResolveRef(this);
    }
}

}
