
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public Test.Items Items {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        Items = new Test.Items(loader("test_items"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        Items.ResolveRef(this);
    }
}

}
