// ═══════════════════════════════════════════════════════════════
// Auto-generated by UIBindCodeGenerator. DO NOT EDIT.
// ═══════════════════════════════════════════════════════════════

using Manager.UIManager;
using UnityEngine;
using UnityEngine.UI;

namespace Game.UI.TestPanel
{
    public class TestPanelNodeProvider : UINodeProvider
    {
        [SerializeField] public Image ImgTest;
    }
}
