using UnityEngine;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using NetFramework.Attributes;
//using NetFramework.Attributes;

public static class NetHandlerGeneratorUtil
{
    public const string SnapshotPath = "Assets/Scripts/Generated/Network/.NetHandlerSnapshot.json";
    public const string GeneratedFile = "Assets/Scripts/Generated/Network/NetHandlerGenerated.cs";

    [Serializable]
    public class HandlerSnapshot
    {
        public List<string> handlers = new List<string>();
    }

    // 🧩 扫描所有 Handler
    public static List<string> ScanHandlers()
    {
        var result = new List<string>();
        var assemblies = AppDomain.CurrentDomain.GetAssemblies();

        foreach (var asm in assemblies)
        {
            Type[] types;
            try { types = asm.GetTypes(); }
            catch (ReflectionTypeLoadException e) { types = e.Types.Where(t => t != null).ToArray(); }

            foreach (var type in types)
            {
                foreach (var method in type.GetMethods(BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic))
                {
                    var attr = method.GetCustomAttribute<NetMessageHandlerAttribute>();
                    if (attr == null) continue;

                    if (!method.IsStatic)
                    {
                        Debug.LogError($"[NetHandlerGenerator] {type.FullName}.{method.Name} 必须是静态方法！");
                        continue;
                    }
                    if (method.GetParameters().Length != 1)
                    {
                        Debug.LogError($"[NetHandlerGenerator] {type.FullName}.{method.Name} 参数数量必须为 1！");
                        continue;
                    }

                    string sig = $"{type.FullName}.{method.Name}:{attr.MsgId}:{attr.MsgType?.FullName ?? "null"}:{attr.ReqMsgType?.FullName ?? "null"}";
                    result.Add(sig);
                }
            }
        }

        result.Sort();
        return result;
    }

    // 🔎 读取快照
    public static List<string> LoadSnapshot()
    {
        if (!File.Exists(SnapshotPath)) return new List<string>();
        try
        {
            var json = File.ReadAllText(SnapshotPath);
            var data = JsonUtility.FromJson<HandlerSnapshot>(json);
            return data != null && data.handlers != null ? data.handlers : new List<string>();
        }
        catch
        {
            return new List<string>();
        }
    }

    // 💾 保存快照
    public static void SaveSnapshot(List<string> handlers)
    {
        var data = new HandlerSnapshot { handlers = handlers };
        string json = JsonUtility.ToJson(data, true);
        Directory.CreateDirectory(Path.GetDirectoryName(SnapshotPath));
        File.WriteAllText(SnapshotPath, json, new UTF8Encoding(false));
    }

    // 🧱 生成注册代码
    public static void GenerateCode(List<string> signatures)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(GeneratedFile));

        var sb = new StringBuilder();
        sb.AppendLine("// ------------------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This code was generated by NetHandlerGeneratorUtil.");
        sb.AppendLine("// ------------------------------------------------------------------------------");
        sb.AppendLine("using System;");
        sb.AppendLine("using NetFramework;");
        sb.AppendLine("using NetFramework.Core;");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();
        sb.AppendLine("public static class NetHandlerGenerated");
        sb.AppendLine("{");
        sb.AppendLine("    public static void RegisterAll()");
        sb.AppendLine("    {");

        foreach (var sig in signatures)
        {
            var parts = sig.Split(':');
            string id = parts[0];
            int cmd = int.Parse(parts[1]);
            if (parts[3] != "null")
            {
                sb.AppendLine($"        NetworkManager.Instance.Dispatcher.Register<{parts[2]},{parts[3]}>({cmd}, {id.Replace('+', '.')});");
            }
            else
            {
                sb.AppendLine($"        NetworkManager.Instance.Dispatcher.Register<{parts[2]}>({cmd}, {id.Replace('+', '.')});");
            }

        }

        sb.AppendLine($"        Debug.Log(\"[AutoNetHandler] 已注册 {signatures.Count} 个网络回调方法\");");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        File.WriteAllText(GeneratedFile, sb.ToString(), new UTF8Encoding(false));
    }
}
